### ISSUE TITLE
OpenAPI Definition loves application/ocet-stream

### ISSUE THREAD

**Issue by boun** [potassco/clingo-server#29]
Hi,

we generate a java client using the openapi definition downloaded from the swagger endpoint of clingo-server. However the generated openapi definiton contains appliction-octect stream instead of application-json for endpoints such as ground. When calling ground() with a generated function the server then responds with a 404, was the ground endpoint does not expect an octet stream. 

Is this a bug in the upstream crate or did you choose that definition somewhere (and if why ;-)?

Best regards
Benedikt

**Comment by sthiele** [comment]
Yep, ground should be `application/json` it is defined here https://github.com/potassco/clingo-server/blob/b6a0e985cf61a790bca45e62075e7e5212fabb0d/src/main.rs#L59.

Looks like a bug in the openapi generator.
This is all very experimental and the libraries I use in this branch are also experimental.

**Comment by sthiele** [comment]
Looking at it some more it seens like I have not implemented the proper json input format :pensive: .
The end point uses octet stream I fixed the annotation so that it should be accepted now.
